services:
  postgres-cache-example:
    image: postgres:17.5
    environment:
      - POSTGRES_DB=example_cache_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  redis:
    image: redis:8.0.2
    ports:
      - "6379:6379"